name             'server'
maintainer       'Sam Soffes'
maintainer_email 'sam@soff.es'
license          'All rights reserved'
description      'Installs/Configures server'
long_description 'Installs/Configures server'
version          '0.1.0'

depends 'git'
depends 'sudo'
depends 'nginx'
depends 'rbenv'
depends 'redis'
