name             'server'
maintainer       'Sam Soffes'
maintainer_email 'sam@soff.es'
license          'MIT'
description      'Installs/Configures server'
long_description 'Installs/Configures server'
version          '0.1.0'
